### ISSUE TITLE
How to modify main.ts?

### ISSUE THREAD

**Issue by robhester** [zone99dev/scrypted-nanit#18]
I'm sorry, this isn't a bug but I'm struggling with the documentation.  There is a suggestion about how to modify the "battery" nature of the camera.  I can't figure out how to access main.ts either via home-assistant / scrypted UI, or via storage.  Any suggestions?  

Again - apologies for using issues this way. Feel free to close as fixed if this isn't an appropriate use of issues! Thanks. 

> If you want to disable this. Remove the ScryptedInterface.Battery from line main.ts.
> 
> ```const interfaces = [
>                 ScryptedInterface.Camera,
>                 ScryptedInterface.VideoCamera,
>                 ScryptedInterface.MotionSensor,
>                 ScryptedInterface.Battery //REMOVE THIS
>             ];```

**Comment by zone99dev** [comment]
How are you installing the plugin?

 Those instructions are meant if you are manually adding it. They since brought it in as a supported plugin and you can’t change it that way

**Comment by robhester** [comment]
Ah, got it - yeah, I  installed directly via Scrypted.  Makes sense ^^ and no problem.  Thanks!
