### ISSUE TITLE
remote npx auth

### ISSUE THREAD

**Issue by PR3SIDENT** [zone99dev/scrypted-nanit#4]
If you're deploying this on a remote instance or seperate Scrypted install then the command is "npx scrypted login <ip:port>"

May be useful for the instructions! Also, do you plan to publish this to the official scrypted plugin directory?

**Comment by zone99dev** [comment]
added that to the readme. Eventually it would be nice to get it as an official scrypted plugin, but i need to fix some of the issues at the bottom of the readme first.
