### ISSUE TITLE
15s delay

### ISSUE THREAD

**Issue by nagydavid** [zone99dev/scrypted-nanit#7]
Hi, 

First of all thanks for the repo. 
i have approx 15s delay to the app. I’m running scripted in docker on Ubuntu server. I wonder is there any way to reduce the delay to HA?

**Comment by Jon-Bolt** [comment]
Can you try the rtsp stream in something like VLC?

if VLC has the 15s delay then it means it’s scrypted that’s the culprit and you can tweet some setting in the rstp rebroadcast plugin. 

If there is not a 15s delay with VLC, then it’s HA. Make sure that HA isn’t trying to encode the stream. I’d also try both methods from readme and see if one works better.

**Comment by zone99dev** [comment]
Can you try the rtsp stream in something like VLC?

if VLC has the 15s delay then it means it’s scrypted that’s the culprit and you can tweet some setting in the rstp rebroadcast plugin.

If there is not a 15s delay with VLC, then it’s HA. Make sure that HA isn’t trying to encode the stream. I’d also try both methods from readme and see if one works better.

**Comment by ajagnanan** [comment]
This is happening to me too. VLC has a 2sec delay. How do you check if HA is encoding the stream?

**Comment by zone99dev** [comment]
https://community.home-assistant.io/t/delay-with-camera-stream/136186/13
https://community.home-assistant.io/t/2-minute-stream-delay/185762

Check out these two links above. 

If that doesn't work post the Camera config and I can try to help debug.

**Comment by nagydavid** [comment]
Thanks for the answer, the go2rtc did the trick. now the delay is 1s>.

**Comment by ajagnanan** [comment]
@nagydavid How did you manage to fix it?

**Comment by nagydavid** [comment]
@ajagnanan i did it using the go2rtc add-on and webrtc hacs integration.

Adding the streams

stream:
  nanit_monitor: <your_rstp_address>


In your ui:

type: "custom:webrtc-camera"
url: nanit_monitor

**Comment by ajagnanan** [comment]
OMG what a difference. I'm getting near realtime (1-2 sec) delay with this method. 
The `stream` is added in the `go2rtc` GUI, I added a `Temporary stream`. Afterwards, add the card to a dashboard with the name matching the `stream` name. This doesn't create entities for use within HA. I wonder if that's possible....
